### ISSUE TITLE
DSO missing from command line

### ISSUE THREAD

**Issue by Harrypys** [ai4ce/peac#2]
When I built the project file it showed up the following error
Does this mean the boost library is not correctly linked to the cpp file?
I tried to modify the CMakeLists.txt but it doesn't work

`make
Scanning dependencies of target plane_fitter_pcd
[ 12%] Building CXX object CMakeFiles/plane_fitter_pcd.dir/plane_fitter_pcd.cpp.o
[ 25%] Linking CXX executable plane_fitter_pcd
/usr/bin/ld: CMakeFiles/plane_fitter_pcd.dir/plane_fitter_pcd.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/plane_fitter_pcd.dir/build.make:118: recipe for target 'plane_fitter_pcd' failed
make[2]: *** [plane_fitter_pcd] Error 1
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/plane_fitter_pcd.dir/all' failed
make[1]: *** [CMakeFiles/plane_fitter_pcd.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

Thanks for any suggestion

**Comment by simbaforrest** [comment]
I was using the pre-compiled PCL (1.8) on Windows that comes with a boost distribution. I have not had a chance to test this on Linux yet. It does look like something was wrong with boost library not properly linked to the project.  You will have to figure out how to add the boost library in CMake, or you can simply write your own Makefile.

Since I have no time to test the Linux building process probably in the next few months, I am closing this issue for now. If you resolved the issue or have additional questions, feel free to make additional comments.

**Comment by Harrypys** [comment]
It turned out that there were some old versions of libboost related files in the lib folder that I had to remove them manually. The linkage issue was solved after I cleaned out the folder
